name: Build

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: event_store
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Check code style
        run: vendor/bin/phpcs

      - name: Run unit tests
        run: vendor/bin/phpunit --testsuite unit

      - name: Import schema into database
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port 33306 -uroot -ppassword event_store < schema.sql

      - name: Run integration tests
        run: vendor/bin/phpunit --testsuite integration
